version: "2.1"
services:
  jekyll:
    image: jekyll/jekyll:pages
    volumes:
      - .:/srv/jekyll
    command: ['jekyll', 'serve', '--watch']
    environment:
      VERBOSE: 'true'

  php:
    build:
      context: ./docker/conf/php
      args:
        uid: "${CURRENT_UID:-1000}"
        gid: "${CURRENT_GID:-1000}"
    volumes:
      - .:/srv/jekyll
